export const EXPENSE_CATEGORIES = [
  'RENT',
  'ELECTRICITY',
  'WATER',
  'INTERNET',
  'PHONE',
  'SUPPLIES',
  'EQUIPMENT',
  'MARKETING',
  'SALARY_EXTRA',
  'TRANSPORT',
  'PACKAGING',
  'SOFTWARE',
  'CLEANING',
  'TAX',
  'BANK_FEE',
  'INSURANCE',
  'MAINTENANCE',
  'FOOD_STAFF',
  'OTHER',
] as const;

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

export const CATEGORY_EMOJI: Record<string, string> = {
  RENT:         '🏠',
  ELECTRICITY:  '⚡',
  WATER:        '💧',
  INTERNET:     '📶',
  PHONE:        '📱',
  SUPPLIES:     '📦',
  EQUIPMENT:    '🔧',
  MARKETING:    '📣',
  SALARY_EXTRA: '👥',
  TRANSPORT:    '🛵',
  PACKAGING:    '🛍️',
  SOFTWARE:     '💻',
  CLEANING:     '🧹',
  TAX:          '🏛️',
  BANK_FEE:     '🏦',
  INSURANCE:    '🛡️',
  MAINTENANCE:  '🔩',
  FOOD_STAFF:   '🍜',
  OTHER:        '🏷️',
};
